module "datadog_aws_integration" {
  source = "../../"

  # Restrict metric collection to specific namespaces.
  # Remove this to collect all AWS CloudWatch namespaces (the default).
  namespace_filters_include_only = [
    "AWS/ACMPrivateCA",
    "AWS/AmazonMQ",
    "AWS/AmplifyHosting",
    "AWS/ApiGateway",
    "AWS/AppFlow",
    "AWS/AppRunner",
    "AWS/AppStream",
    "AWS/AppSync",
    "AWS/Athena",
    "AWS/AutoScaling",
    "AWS/Backup",
    "AWS/Billing",
    "AWS/Cassandra",
    "AWS/CertificateManager",
    "AWS/Chatbot",
    "AWS/ChimeSDK",
    "AWS/ChimeVoiceConnector",
    "AWS/ClientVPN",
    "AWS/CloudFront",
    "AWS/CloudHSM",
    "AWS/CloudSearch",
    "AWS/CloudTrail",
    "AWS/CloudWatch/MetricStreams",
    "AWS/CodeBuild",
    "AWS/Cognito",
    "AWS/Comprehend",
    "AWS/Config",
    "AWS/Connect",
    "AWS/DAX",
    "AWS/DDoSProtection",
    "AWS/DMS",
    "AWS/DataLifecycleManager",
    "AWS/DataSync",
    "AWS/DevOps-Guru",
    "AWS/DirectoryService",
    "AWS/DocDB",
    "AWS/DynamoDB",
    "AWS/DX",
    "AWS/EBS",
    "AWS/EC2",
    "AWS/ECS",
    "AWS/EKS",
    "AWS/ElastiCache",
    "AWS/Lambda",
    "AWS/RDS",
    "AWS/S3",
  ]
}
